### ISSUE TITLE
clock positioning

### ISSUE THREAD

**Issue by foxyloxy-eng** [stefan-oskamp/DeskClock#1]
When I first installed the clock was too low in the taskbar and part of the bottom of the clock was not visible.
Figuring it was something to do with resolution (I normally use 2560x1440) I resized to 1920x1080 and it was fixed.
I then resized again to 2560*1440 and it was fixed again.

**Comment by stefan-oskamp** [comment]
Thanks for the note.

**Comment by ofermar** [comment]
I installed on a Hebrew language Windows 10, and the clock is displayed mirrored, with the seconds hand rotating counter-clockwise. Could you fix this, please?

**Comment by stefan-oskamp** [comment]
@ofermar, I am now using Linux. I still can boot into Windows, but I have updated it from Windows 10 to Windows 11, and there Microsoft has removed toolbars on the taskbar. (Less is more seems to be their motto, but I wouldn't agree.) So, sadly, I am not able to fix the issue.

It seems the issue might be fixed by calling SetProcessDefaultLayout(LAYOUT_LTR) as describe [here](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-features#window-layout-and-mirroring). If you have the chance to build and test the clock toolbar, I could support you with some practical advice.

If you plan on migrating to Windows 11, then keep in mind that you wouldn't be abe to use the clock there anymore.

**Comment by ofermar** [comment]
Thank you, @stefan-oskamp ! 
I have finally gotten around to attempt implementing your suggestion, and have set up the necessary tools (I hope...).
I'd appreciate more specific directions:
In which of the files should I place the call to SetProcessDefaultLayout(LAYOUT_LTR) and specifically where within the file(s)?

**Comment by stefan-oskamp** [comment]
Hi @ofermar,
Sorry for the delay. Maybe you have tried on your own already. If not, I suggest to look into DeskClock.cpp and place the call either before or after the call to GdiplusStartup () in line 34.
Also, in the main Readme under "Installation", there is a list of steps for manual installation (without rebootting), which makes debugging much easier. You can even run the Explorer command in the debugger if you stop it (close the desktop) before starting to debug. Just make sure that Explorer loads the right  DLL (the debug version you just compiled) when you start it in your debugger.
Good luck!
Stefan

**Comment by ofermar** [comment]
Hi @stefan-oskamp,
Thank you for your informative help.
I made the changes you suggested and compiled, but unfortunately the clock was still mirrored.
If would gladly take other suggestions, if you have any...

**Comment by stefan-oskamp** [comment]
Hi @ofermar ,
Sorry, no further ideas as to how to get that right. But a rather simple hack would be change the calculations where the angle of each hand is derived from the current time.
Regards,
Stefan

**Comment by ofermar** [comment]
Thank you very much @stefan-oskamp !
[EDIT]:
I negated all multipliers (added a "-") in the Rotate commands and now it is displayed **correctly** and looks VERY COOL on my system. 
Thanks again for this beautiful clock and for the guidance in making it work properly.
Regards and be well,
Ofer
