### ISSUE TITLE
Have a big clock when you click the date in the bottom right

### ISSUE THREAD

**Issue by LordWolfenstein** [stefan-oskamp/DeskClock#2]
Back in Windows 7 and before you got a big analog clock when you click in the bottom right of the taskbar. It is possible to make that feature return? To have it replace the digital clock you get?

Kind of like this image.
![image](https://user-images.githubusercontent.com/27807240/150399155-9219fb1c-b16c-4f1d-af7d-bea876fe9984.png)

**Comment by stefan-oskamp** [comment]
I think it would be possible to do something like that in the DeskClock toolbar, i.e. popup a window with a bigger clock when you click on the analog clock in the taskbar.

You would have to clone the repo and try it on your own, because (a) I switched to Linux now and (b) Windows 11 no longer supports toolbars on the taskbar.

Or you move your taskbar to the left (or right) edge of the screen. With todays 16:9 screens that makes more sense, anyway.

**Comment by stefan-oskamp** [comment]
No development of new functionality planned.
